name: PSE Auto Trade Bot

on:
  workflow_dispatch: # Nagpapahintulot sa iyo na patakbuhin ito nang manu-mano gamit ang isang button

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run Bot
      env:
        INVESTA_USERNAME: ${{ secrets.INVESTA_USERNAME }}
        INVESTA_PASSWORD: ${{ secrets.INVESTA_PASSWORD }}
      run: python investa_bot.py
